before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: XXkpNeDfPujU7xAh9lJMuIFGDmLDB49efSFY79Ih+UxXDne2KM5XNhLIme2XZOWCeHZmaELwllSD3Owo/pAVibUXAyy96HGyacq2V6thvXJGTQX6Ly2M5+SrZlSPReooQa3BEDJ3O/6NE91pRBJoIQEb+cvEOri4Vcs23edDVCk9+Oeb1PdYZnv8PXYnEiwUkrZfmu+zECJUZSTR52Y+MGlU1FXj7Zg/g1gX65KSeQJZzTIBd7CYQdmGpCqlgeFomn2hmZ6pAEMTJtxiKADx2dtKdC4S+CQQgMkYfHHmDxseC580BQLF6nHrlaTAWNWJsXXlHRrBDoOaNqxy1sYWdQ5H+SGRju3T9PGdRcdUfhGL67aV/4kgnEIS0qzc8OXdpVIGVqxJLhBYObqz7ZRWOnFxSoX0TS6c4T+H5I8uaTwz2X/uUXsxydFQaldDQ5M9npuq54aq+Z4IRI1+Xf+jyfz4JBuVc+vGAIBMN85kw6YfF+83ofl7xVQ/xl1HAhIa639/Dcghhypn3Av+gJ9RyXS4yaMXHg1oh/5BXsRKz1DXxnqj6x1WojyRsU0ZQWZj56w2JQS/DoSECZ9DB8PJiL2sH+KDwFksMFtXU1z57Oq0MlnkBZAxX15coWeQeG8GuCBAmtEzp5DChQmTnF3dtAiKBCUFaoiupJbULWfBV2o= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
